services:
  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    image: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - ./requirements/nginx/tools:/etc/nginx/ssl/
      - wp-volume:/var/www/
    networks:
      - inception
    restart: always

  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_ROOT: ${DB_ROOT}
    container_name: mariadb
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_HOST: ${DB_HOST}
        WP_TITLE: ${WP_TITLE}
        ADM_WP_NAME: ${ADM_WP_NAME}
        ADM_WP_PASS: ${ADM_WP_PASS}
        ADM_WP_EMAIL: ${ADM_WP_EMAIL}
        WP_USERNAME: ${WP_USERNAME}
        WP_USEREMAIL: ${WP_USEREMAIL}
        WP_USERPASS: ${WP_USERPASS}
        WP_HOST: ${WP_HOST}
    container_name: wordpress
    image: wordpress
    depends_on:
      - mariadb
    volumes:
      - wp-volume:/var/www/
    networks:
      - inception
    restart: always

volumes:
  wp-volume:
    name: wordpress
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress

  db-volume:
    name: mariadb
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb
  
networks:
    inception:
        name: inception
        driver: bridge